#!/usr/bin/env node
/**
 * Warehouse MCP Server — stdio transport.
 *
 * Exposes all foodwarehouse API operations as MCP tools so that any
 * MCP-compatible client (Claude Desktop, our orchestrator, etc.) can use them.
 *
 * Env vars required:
 *   HUB_APIKEY — Centrala API key
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import * as hub from "./hub.js";

const apikey = process.env.HUB_APIKEY?.trim();
if (!apikey) {
  process.stderr.write("ERROR: HUB_APIKEY env var is required\n");
  process.exit(1);
}

const server = new McpServer(
  { name: "warehouse-mcp", version: "1.0.0" },
  { capabilities: { tools: {} } },
);

// ── Informational ────────────────────────────────────────────────────────────

server.tool(
  "get_help",
  "Get the full API documentation for the foodwarehouse task including available tools, parameters and examples.",
  {},
  async () => {
    const res = await hub.getHelp(apikey);
    return { content: [{ type: "text", text: JSON.stringify(res.data, null, 2) }] };
  },
);

server.tool(
  "get_food_requirements",
  "Fetch food4cities.json — the list of cities and the exact goods/quantities each city needs.",
  {},
  async () => {
    const data = await hub.getFoodRequirements();
    return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] };
  },
);

// ── Database ─────────────────────────────────────────────────────────────────

server.tool(
  "query_database",
  "Execute a read-only SQL query against the SQLite database. Use 'show tables' to list tables, or any SELECT statement. Returns raw API response.",
  {
    query: z
      .string()
      .describe("SQL query, e.g. 'show tables' or 'SELECT * FROM users'"),
  },
  async ({ query }) => {
    const res = await hub.queryDatabase(apikey, query);
    return { content: [{ type: "text", text: JSON.stringify(res.data, null, 2) }] };
  },
);

// ── Orders ───────────────────────────────────────────────────────────────────

server.tool(
  "get_orders",
  "List all currently created orders with their IDs, titles, destinations and items.",
  {},
  async () => {
    const res = await hub.getOrders(apikey);
    return { content: [{ type: "text", text: JSON.stringify(res.data, null, 2) }] };
  },
);

server.tool(
  "create_order",
  "Create a new delivery order. You must know the creatorID, destination code, and valid SHA1 signature before calling this.",
  {
    title: z.string().describe("Human-readable order title, e.g. 'Dostawa dla Gdańska'"),
    creatorID: z.number().int().describe("User ID of the order creator (from SQLite)"),
    destination: z
      .string()
      .describe("Destination code for the target city (from SQLite)"),
    signature: z
      .string()
      .describe("SHA1 signature generated by generate_signature for this creatorID"),
  },
  async ({ title, creatorID, destination, signature }) => {
    const res = await hub.createOrder(apikey, { title, creatorID, destination, signature });
    return { content: [{ type: "text", text: JSON.stringify(res.data, null, 2) }] };
  },
);

server.tool(
  "append_items",
  "Add items to an existing order in batch mode. Pass an object mapping item names to quantities. If an item already exists, its quantity is increased.",
  {
    id: z.string().describe("Order ID returned by create_order"),
    items: z
      .record(z.string(), z.number().int())
      .describe("Object mapping item name → quantity, e.g. {\"chleb\": 45, \"woda\": 120}"),
  },
  async ({ id, items }) => {
    const res = await hub.appendItems(apikey, { id, items });
    return { content: [{ type: "text", text: JSON.stringify(res.data, null, 2) }] };
  },
);

// ── Signature ────────────────────────────────────────────────────────────────

server.tool(
  "generate_signature",
  "Generate the SHA1 signature required when creating an order. The signature is unique per (login, birthday, destination) combination — call it once per city order. login and birthday come from the SQLite users table; destination is the numeric city code.",
  {
    login: z.string().describe("User login from the SQLite users table"),
    birthday: z
      .string()
      .describe("User birthday in YYYY-MM-DD format from the SQLite users table"),
    destination: z
      .number()
      .int()
      .describe("Numeric destination code of the target city (from SQLite)"),
  },
  async ({ login, birthday, destination }) => {
    const res = await hub.generateSignature(apikey, { login, birthday, destination });
    // Flatten the response so the "hash" field is clearly visible at top level
    const out = { ...res.data, signature: res.data?.hash };
    return { content: [{ type: "text", text: JSON.stringify(out, null, 2) }] };
  },
);

// ── Control ──────────────────────────────────────────────────────────────────

server.tool(
  "reset_orders",
  "Reset all orders back to the initial empty state. Use only when something went wrong and you need a clean start.",
  {},
  async () => {
    const res = await hub.resetState(apikey);
    return { content: [{ type: "text", text: JSON.stringify(res.data, null, 2) }] };
  },
);

server.tool(
  "finalize",
  "Submit the final verification request. Call this only when ALL orders are fully created and populated with the correct items. Returns a flag on success.",
  {},
  async () => {
    const res = await hub.callDone(apikey);
    process.stderr.write(`\n[MCP finalize] HTTP ${res.status}: ${JSON.stringify(res.data)}\n`);
    return { content: [{ type: "text", text: JSON.stringify(res.data, null, 2) }] };
  },
);

// ── Start ────────────────────────────────────────────────────────────────────

const transport = new StdioServerTransport();
await server.connect(transport);

const shutdown = async () => {
  await server.close();
  process.exit(0);
};
process.on("SIGINT", shutdown);
process.on("SIGTERM", shutdown);
